language: csharp

sudo: false  # use the new container-based Travis infrastructure 
dist: trusty #ubuntu 14.04 requierd by .net sdk 1.0
mono: latest
dotnet: 3.0.0

script: 
  - ./build.sh BuildPackage